<a href="https://colab.research.google.com/github/Nayoumi/Audio_Analysis/blob/main/AI_ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [273]:
# importing libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [274]:
#reading the data from csv file
twitter_data = pd.read_csv(r"/content/Tweets.csv")

In [275]:
#displaying rows and columns 1st five
twitter_data.head()

tweet_id  ...               user_timezone
0  570306133677760000  ...  Eastern Time (US & Canada)
1  570301130888122000  ...  Pacific Time (US & Canada)
2  570301083672813000  ...  Central Time (US & Canada)
3  570301031407624000  ...  Pacific Time (US & Canada)
4  570300817074462000  ...  Pacific Time (US & Canada)

[5 rows x 15 columns]

In [276]:
#number of rows and columns
twitter_data.shape

(14640, 15)

In [277]:
#displaying column names
twitter_data.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='object')

In [278]:
#information about the data frame
twitter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   tweet_id                      14640 non-null  int64  
 1   airline_sentiment             14640 non-null  object 
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   object 
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  object 
 6   airline_sentiment_gold        40 non-null     object 
 7   name                          14640 non-null  object 
 8   negativereason_gold           32 non-null     object 
 9   retweet_count                 14640 non-null  int64  
 10  text                          14640 non-null  object 
 11  tweet_coord                   1019 non-null   object 
 12  tweet_created                 14640 non-null  object 
 13  t

### Displaying Unique values of the column

In [279]:
print("Airline_sentiment: \n",twitter_data["airline_sentiment"].unique())
print("negativereason:\n",twitter_data["negativereason"].unique())
print("airline:\n",twitter_data["airline"].unique())
print("airline_sentiment_gold  :\n",twitter_data["airline_sentiment_gold"].unique())
#print("name  :\n",twitter_data["name"].unique())
print("negativereason_gold: \n",twitter_data["negativereason_gold"].unique())
print("retweet_count: \n",twitter_data["retweet_count"].unique())
#print("text: \n",twitter_data["text"].unique())
print("tweet_created: \n",twitter_data["tweet_created"].unique())
print("tweet_location: \n",twitter_data["tweet_location"].unique())
print("user_timezone: \n",twitter_data["user_timezone"].unique())
#print("tweet_coord: \n",twitter_data["tweet_coord"].unique())

Airline_sentiment: 
 ['neutral' 'positive' 'negative']
negativereason:
 [nan 'Bad Flight' "Can't Tell" 'Late Flight' 'Customer Service Issue'
 'Flight Booking Problems' 'Lost Luggage' 'Flight Attendant Complaints'
 'Cancelled Flight' 'Damaged Luggage' 'longlines']
airline:
 ['Virgin America' 'United' 'Southwest' 'Delta' 'US Airways' 'American']
airline_sentiment_gold  :
 [nan 'negative' 'neutral' 'positive']
negativereason_gold: 
 [nan 'Late Flight\nFlight Attendant Complaints'
 'Late Flight\nLost Luggage' 'Late Flight' 'Customer Service Issue'
 "Can't Tell" 'Cancelled Flight\nCustomer Service Issue'
 'Cancelled Flight' 'Bad Flight' 'Lost Luggage\nDamaged Luggage'
 'Late Flight\nCancelled Flight' 'Flight Attendant Complaints'
 'Customer Service Issue\nLost Luggage'
 "Customer Service Issue\nCan't Tell"]
retweet_count: 
 [ 0  1  2  3  4  5  7 22  6 18 15 31 11  8  9 28 32 44]
tweet_created: 
 ['2015-02-24 11:35:52 -0800' '2015-02-24 11:15:59 -0800'
 '2015-02-24 11:15:48 -0800' ... '2015

### Count of null values for each column

In [280]:
twitter_data.isna().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

### Converting the string data to numerical using label encoder, the text data is converted to numerical form.

In [281]:
label_encoder = LabelEncoder()
label_encoder.fit(twitter_data["airline_sentiment"])
twitter_data["airline_sentiment"]= label_encoder.transform(twitter_data["airline_sentiment"])
label_encoder.fit(twitter_data["negativereason"])
twitter_data["negativereason"]= label_encoder.transform(twitter_data["negativereason"])
label_encoder.fit(twitter_data["airline"])
twitter_data["airline"]= label_encoder.transform(twitter_data["airline"])
label_encoder.fit(twitter_data["user_timezone"])
twitter_data["user_timezone"]= label_encoder.transform(twitter_data["user_timezone"])
label_encoder.fit(twitter_data["tweet_location"])
twitter_data["tweet_location"]= label_encoder.transform(twitter_data["tweet_location"])
label_encoder.fit(twitter_data["text"])
twitter_data["text"]= label_encoder.transform(twitter_data["text"])

### Dropping the columns

In [282]:
twitter_data.drop("negativereason_gold",axis=1,inplace=True)
twitter_data.drop("airline_sentiment_gold",axis=1,inplace=True)
twitter_data.drop("tweet_coord",axis=1,inplace=True)
twitter_data.drop("name",axis=1,inplace=True)
twitter_data.drop("tweet_id",axis=1, inplace=True)

In [283]:
twitter_data.shape

(14640, 10)

### converting the object column to datetime

In [284]:
twitter_data['tweet_created']= pd.to_datetime(twitter_data['tweet_created'])

In [285]:
twitter_data.tweet_created

0       2015-02-24 11:35:52-08:00
1       2015-02-24 11:15:59-08:00
2       2015-02-24 11:15:48-08:00
3       2015-02-24 11:15:36-08:00
4       2015-02-24 11:14:45-08:00
                   ...           
14635   2015-02-22 12:01:01-08:00
14636   2015-02-22 11:59:46-08:00
14637   2015-02-22 11:59:15-08:00
14638   2015-02-22 11:59:02-08:00
14639   2015-02-22 11:58:51-08:00
Name: tweet_created, Length: 14640, dtype: datetime64[ns, pytz.FixedOffset(-480)]

### Seperating Day, Month, Year columns

In [286]:
twitter_data['day'] = twitter_data['tweet_created'].dt.day
twitter_data['month'] = twitter_data['tweet_created'].dt.month
twitter_data['year'] = twitter_data['tweet_created'].dt.year

### Droping the original date column

In [287]:
twitter_data.drop("tweet_created",axis=1,inplace=True)

In [288]:
twitter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   airline_sentiment             14640 non-null  int64  
 1   airline_sentiment_confidence  14640 non-null  float64
 2   negativereason                14640 non-null  int64  
 3   negativereason_confidence     10522 non-null  float64
 4   airline                       14640 non-null  int64  
 5   retweet_count                 14640 non-null  int64  
 6   text                          14640 non-null  int64  
 7   tweet_location                14640 non-null  int64  
 8   user_timezone                 14640 non-null  int64  
 9   day                           14640 non-null  int64  
 10  month                         14640 non-null  int64  
 11  year                          14640 non-null  int64  
dtypes: float64(2), int64(10)
memory usage: 1.3 MB


In [289]:
twitter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   airline_sentiment             14640 non-null  int64  
 1   airline_sentiment_confidence  14640 non-null  float64
 2   negativereason                14640 non-null  int64  
 3   negativereason_confidence     10522 non-null  float64
 4   airline                       14640 non-null  int64  
 5   retweet_count                 14640 non-null  int64  
 6   text                          14640 non-null  int64  
 7   tweet_location                14640 non-null  int64  
 8   user_timezone                 14640 non-null  int64  
 9   day                           14640 non-null  int64  
 10  month                         14640 non-null  int64  
 11  year                          14640 non-null  int64  
dtypes: float64(2), int64(10)
memory usage: 1.3 MB


### Converting columns to float datatype

In [290]:
twitter_data['airline_sentiment'] = twitter_data['airline_sentiment'].astype(float)
twitter_data['negativereason'] = twitter_data['negativereason'].astype(float)
twitter_data['airline_sentiment'] = twitter_data['airline_sentiment'].astype(float)
twitter_data['retweet_count'] = twitter_data['retweet_count'].astype(float)
twitter_data['text'] = twitter_data['text'].astype(float)
twitter_data['tweet_location'] = twitter_data['tweet_location'].astype(float)
twitter_data['user_timezone'] = twitter_data['user_timezone'].astype(float)
twitter_data['day'] = twitter_data['day'].astype(float)
twitter_data['month'] = twitter_data['month'].astype(float)
twitter_data['year'] = twitter_data['year'].astype(float)
twitter_data['airline'] = twitter_data['airline'].astype(float)

### After cleaning the data displaying the information of the data frame

In [291]:
twitter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   airline_sentiment             14640 non-null  float64
 1   airline_sentiment_confidence  14640 non-null  float64
 2   negativereason                14640 non-null  float64
 3   negativereason_confidence     10522 non-null  float64
 4   airline                       14640 non-null  float64
 5   retweet_count                 14640 non-null  float64
 6   text                          14640 non-null  float64
 7   tweet_location                14640 non-null  float64
 8   user_timezone                 14640 non-null  float64
 9   day                           14640 non-null  float64
 10  month                         14640 non-null  float64
 11  year                          14640 non-null  float64
dtypes: float64(12)
memory usage: 1.3 MB


### Spliting the data into input and output , features and target

In [292]:
twitter_features= twitter_data.drop("airline_sentiment",axis=1)
twitter_target =twitter_data.airline_sentiment

In [293]:
print(twitter_target.unique())  #1 is neutral, 2 is positive and 0 is negative

[1. 2. 0.]


### Filling NaN with zeros

In [294]:
twitter_features=twitter_features.fillna(0)

In [295]:
twitter_features.head()

airline_sentiment_confidence  negativereason  ...  month    year
0                        1.0000            10.0  ...    2.0  2015.0
1                        0.3486            10.0  ...    2.0  2015.0
2                        0.6837            10.0  ...    2.0  2015.0
3                        1.0000             0.0  ...    2.0  2015.0
4                        1.0000             1.0  ...    2.0  2015.0

[5 rows x 11 columns]

### Spliting the dataset into trai and test data

In [296]:
trainx,testx,trainy,testy=train_test_split(twitter_features,twitter_target,test_size=0.3,random_state=40)

### Randomforest classifier algorithm

In [297]:
r_model=RandomForestClassifier()
r_model.fit(trainx,trainy)

RandomForestClassifier()

In [298]:
y_predict=r_model.predict(testx)

### Confusion metrics

In [299]:
r_cm = confusion_matrix(y_predict, testy)
r_cm

array([[2781,    0,    0],
       [   0,  680,  345],
       [   0,  269,  317]])

### Test and train acuuracy 

In [300]:
print("test_accuracy",np.round(accuracy_score(y_predict, testy)*100,2),"%")
print("train_accuracy",np.round(accuracy_score(lr_model.predict(trainx), trainy)*100,2),"%")

test_accuracy 86.02 %
train_accuracy 99.98 %


### Decision tree classifier

In [301]:
dt_model1=DecisionTreeClassifier()
dt_model1.fit(trainx,trainy)

DecisionTreeClassifier()

In [302]:
y_predict=dt_model1.predict(testx)

### Confusion metrics

In [303]:
dt_cm = confusion_matrix(y_predict, testy)
dt_cm

array([[2781,    0,    0],
       [   0,  566,  298],
       [   0,  383,  364]])

### Test and train accuracy

In [304]:
print("test_accuracy",np.round(accuracy_score(y_predict, testy)*100,2),"%")
print("train_accuracy",np.round(accuracy_score(lr_model.predict(trainx), trainy)*100,2),"%")

test_accuracy 84.49 %
train_accuracy 99.98 %
